In [15]:
import torch
import torch.nn as nn
import numpy as np

In [27]:
data = np.array([[1., 3., 2.]])
print(data.shape)

(1, 3)


In [56]:
torch.Tensor([1., 3., 2.]).reshape((3, 1)).shape

torch.Size([3, 1])

In [57]:
data = torch.Tensor([1., 3., 2.]).reshape((3, 1))
num_heads, embed_dim = 1, 2
multihead_attn = nn.MultiheadAttention(embed_dim, num_heads)
attn_output, attn_output_weights = multihead_attn(data, data, data)

AssertionError: was expecting embedding dimension of 2, but got 1

In [30]:
q = np.array([[0.4,  0.3],
              [-0.1, -0.1],
              [ 0.2, -0.1]])
k = np.array([[ 0.1,  0.2 ],
              [-0.3, -0.4],
              [-0.1,  0.2]])
v = np.array([[-0.2,  0.1],
              [-0.4,  0.2],
              [0.4, -0.6]])

print(q.shape)
print(k.shape)
print(v.shape)

(3, 2)
(3, 2)
(3, 2)


In [25]:
q_value = np.dot(data, q)
k_value = np.dot(data, k)
v_value = np.dot(data, v)
 
print(q_value)
print(k_value)
print(v_value)

(1, 2)
[[-1.  -0.6]]
[[-0.6 -0.5]]


In [37]:
def softmax(x):
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum()

alpha = softmax(np.dot(k_value, q_value.T))
alpha

array([[1.]])

In [35]:
np.dot(k_value, q_value.T)

array([[-0.38]])

In [38]:
context_vector = alpha * v_value
print(context_vector)

[[-0.6 -0.5]]


In [39]:
o = np.array([[ 0.1, -0.1,  0.6 ],
              [ 0.9,  0.3,  0.1 ]])
print(o)

[[ 0.1 -0.1  0.6]
 [ 0.9  0.3  0.1]]


In [40]:
output = np.dot(context_vector, o)
print(output)

[[-0.51 -0.09 -0.41]]
