In [34]:
import numpy as np
import matplotlib.pyplot as plt

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [4]:
B = np.array([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B

array([[1, 2, 3],
       [2, 0, 4],
       [3, 4, 5]])

In [5]:
X = np.arange(24).reshape(2, 3, 4)
X

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [6]:
x = np.arange(4)
x, x.sum()

(array([0, 1, 2, 3]), 6)

In [18]:
y = np.ones(4)
x, y, np.dot(x, y)

(array([0, 1, 2, 3]), array([1., 1., 1., 1.]), 6.0)

In [7]:
A.shape, x.shape, np.dot(A, x)

((5, 4), (4,), array([ 14,  38,  62,  86, 110]))

In [13]:
B = np.ones(shape=(4, 3))
print(A)
print(B)
np.dot(A, B)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


array([[ 6.,  6.,  6.],
       [22., 22., 22.],
       [38., 38., 38.],
       [54., 54., 54.],
       [70., 70., 70.]])

In [21]:
u = np.array([3, -4])
u, np.linalg.norm(u)

(array([ 3, -4]), 5.0)

In [23]:
def f(x):
    return 3 * x ** 2 - 4 * x

def numerical_lim(f, x, h):
    return (f(x + h) - f(x)) / h

h = 0.1
for i in range(5):
    print('h=%.5f, numerical limit=%.5f' % (h, numerical_lim(f, 1, h)))
    h *= 0.1

h=0.10000, numerical limit=2.30000
h=0.01000, numerical limit=2.03000
h=0.00100, numerical limit=2.00300
h=0.00010, numerical limit=2.00030
h=0.00001, numerical limit=2.00003
